version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 285951302175.dkr.ecr.us-east-2.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t pal-flask-app .
      - docker tag pal-flask-app:latest 285951302175.dkr.ecr.us-east-2.amazonaws.com/pal-flask-app:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 285951302175.dkr.ecr.us-east-2.amazonaws.com/pal-flask-app:latest
artifacts:
  files: '**/*'
